Long press on the map to create an event at that location
echo-swent/echo pull request #306
Opened 2024-05-16 13:37 UTC by alejandrocalles

2024-05-16 14:51 UTC, ntissieres requested changes
The position seems to stick to the "center" of the map which is in Lausanne - EPFL. The coordinates are not good (at least not where the user long click)

2024-05-16 23:49 UTC, alejandrocalles commented on app/src/main/java/com/github/swent/echo/compose/components/HamburgerMenuDrawerSheet.kt
> +                    val encodedMapCenter = Json.encodeToString(MAP_CENTER)
Solved! The logic for displaying the location in `EventLocationEntry` was skewed.

2024-05-17 06:10 UTC, violoncelloCH approved these changes
great implementation of that quality of life improvement :)
thanks for working on this!
lgtm now

2024-05-17 06:10 UTC, violoncelloCH commented on app/src/main/java/com/github/swent/echo/compose/components/HamburgerMenuDrawerSheet.kt
> +                    val encodedMapCenter = Json.encodeToString(MAP_CENTER)
great, nice solution!

2024-05-17 06:11 UTC, merged