Feature/search tag
echo-swent/echo pull request #41
Opened 2024-04-06 15:33 UTC by srsingh04

This is the code for the UI of the tags. Before I progress further, I need to know whether in our application, the tags which are displayed are fixed from before (like in Spotify) for all users and when someone clicks on one of these tags the sub content inside is personalized or the apps themselves are personalized?

2024-04-10 12:06 UTC, ntissieres commented
I think we need to discuss more in details how we will implement the tag hierarchy, and follow it for the implementation of this feature. Like if there is more than a number of tags from the same category, we could group them and display the parent tag. When the user click on this parent tag, the children would appear. I will clarify it with you tomorrow if it's not clear.

2024-04-10 14:54 UTC, ntissieres requested changes
Maybe it's not a good idea to name the file Tags.kt, we already have a file named Tag to define the data class and moreover it's not truly indicative of what it encodes. MainscreenTagsFilter would be better for example

2024-04-10 15:05 UTC, ntissieres requested changes
Don't forget to remove everything that is commented. In order to merge the code into the main, the code should be clean

2024-04-10 15:53 UTC, violoncelloCH commented on app/src/main/java/com/github/swent/echo/data/model/Tag.kt
> +data class Tag(val tagId: String, val name: String, val isSelected: Boolean)
I'm not sure if having `isSelected` on the data model makes sense. This is state only concerning the UI and nothing we want to store. See also my comment here: https://github.com/echo-swent/echo/pull/31#issuecomment-2047914993

2024-04-12 09:37 UTC, ntissieres requested changes
It's better to remove the padding on the top of the items, it will be done after when we add the search tag to the scaffold

2024-04-12 09:52 UTC, ntissieres approved these changes
Perfect !

2024-04-12 13:21 UTC, merged