navigation between login and register screens
echo-swent/echo pull request #43
Opened 2024-04-09 10:40 UTC by octogradiste

This will close #22.

2024-04-10 12:58 UTC, unglazedstamp requested changes
Very clean code !
just some minor things to change.

2024-04-10 22:32 UTC, octogradiste commented on app/src/androidTest/java/com/github/swent/echo/ui/navigation/NavigationTest.kt
> +    @get:Rule(order = 0) val hiltRule = HiltAndroidRule(this)
I tried to run the tests without, and it doesn't work... My guess is that we need to specify the order, even if we don't actually use the `hiltRule`.

2024-04-10 22:37 UTC, octogradiste commented
Thank you so much for taking the time to review my code :)

2024-04-11 08:50 UTC, unglazedstamp approved these changes
All good, thank you for the improvements !

2024-04-11 08:51 UTC, merged