Implementing email authentication
echo-swent/echo pull request #8
Opened 2024-03-21 08:57 UTC by octogradiste

Using Supabase to implement email authentication (sign in and sign up).
It will contain a basic login and register screen, which can be styled and extended later on.

2024-03-26 13:23 UTC, unglazedstamp requested changes

2024-03-26 18:39 UTC, octogradiste commented on app/src/main/java/com/github/swent/echo/authentication/AuthenticationResult.kt
> +    data object Success : AuthenticationResult()
I like the idea, but for simplicity I think we should leave it like that for now. Maybe in the future, if we see a need for it, we can add it.

2024-03-26 18:39 UTC, octogradiste commented on app/src/main/java/com/github/swent/echo/authentication/AuthenticationServiceImpl.kt
> +    override suspend fun getCurrentUserID(): String? {
You're right, I should change this!

2024-03-27 09:34 UTC, unglazedstamp approved these changes

2024-03-27 15:53 UTC, violoncelloCH approved these changes
lgtm

2024-03-27 15:53 UTC, merged